FROM node:22-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
RUN npx prisma generate

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate deploy && npx nodemon -L --watch src --ext ts,json --exec 'node -r ts-node/register -r tsconfig-paths/register src/main.ts'"]